spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
  error:
    include-message: always
